Profile=//span[text()='Profile']
Login_Signup=//a[text()='login / Signup']
phone_num =//input[@type='tel']
Check_Box=//input[@type='checkbox']
Continue_Button=//div[text()='CONTINUE']

#"" nhi chiye/: nhi chiye/space nhi chiye/
#' chiye/